name: Release

# When tag '*.*.*' is pushed, run this job.
on:
  push:
    tags:
      - "*.*.*"
jobs:
  check-tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: check tag name
        run: test ${{ github.ref }} = `node -e "console.log(require('./package.json').version)"`

  build:
    needs: check-tag-version
    runs-on: ubuntu-latest
    strategy:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: install dependencies
        run: npm ci

      - name: audit
        run: npm audit

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test

      - name: build
        run: npm run build

      - name: publish to npm registry
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
